version: '4.0.0'
services:
  edgeware:
    build:
      context: .
    ports:
      - "0.0.0.0:9933:9933/tcp"
      - "0.0.0.0:9944:9944/tcp"
      - "0.0.0.0:30333:30333/tcp"
    image: eteissonniere/edgeware:latest
    command: bash -c "edgeware --chain=edgeware --name <INSERT NAME> --wasm-execution Compiled"
    volumes:
     - "edgeware-data:/data"
    
volumes:
  edgeware-data:
